[package]
name = "tor-rpcbase"
version = "0.17.0"
edition = "2021"
rust-version = "1.70"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Low level functionality for Arti's RPC service"
keywords = ["tor", "arti", "rpc"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive-deftly = "0.10.3"
downcast-rs = "1.2.0"
erased-serde = "0.4.2"
futures = "0.3.14"
futures-await-test = "0.3.0"
inventory = "0.3.5"
once_cell = "1"
paste = "1"
serde = { version = "1.0.103", features = ["derive"] }
serde_repr = "0.1.12"
thiserror = "1"
tor-async-utils = { path = "../tor-async-utils", version = "0.17.0" }
tor-error = { path = "../tor-error/", version = "0.17.0", features = ["rpc"] }
typetag = "0.2.7"

[dev-dependencies]
assert-impl = "0.1.3"
futures-await-test = "0.3.0"
serde_json = "1.0.50"

[features]
full = ["tor-async-utils/full", "tor-error/full"]
