[package]
name = "tor-dirserver"
version = "0.34.0"
authors = ["The Tor Project, Inc.", "Clara Engler <cve@torproject.org>"]
edition = "2021"
rust-version = "1.83"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Implements dirserver functionality"
keywords = ["tor", "arti"]
# We must put *something* here and this will do
categories = ["rust-patterns"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
bytes = "1.10.1"
deadpool = "0.12.2"
deadpool-sqlite = "0.12.1"
futures = "0.3.31"
http = "1.3.1"
http-body = "1.0.1"
hyper = { version = "1.7.0", default-features = false, features = ["server", "http1"] }
hyper-util = { version = "0.1.16", features = ["full"] }
rusqlite = "0.37.0"
strum = { version = "0.27.1", features = ["derive"] }
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tor-error = { version = "0.34.0", path = "../tor-error" }
tracing = "0.1.41"
weak-table = "0.3.2"

[dev-dependencies]
flate2 = "1.1.2"
hex = "0.4.3"
http-body-util = "0.1.3"
lzma-rs = "0.3.0"
sha2 = "0.10.9"
tokio-stream = { version = "0.1.17", features = ["full"] }
zstd = "0.13.3"
