[package]
name = "tor-memquota-cost"
version = "0.39.0"
authors = ["The Tor Project, Inc.", "Ian Jackson <iwj@torproject.org>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Low-level memory tracking traits, for use by Arti"
keywords = ["tor", "arti"]
categories = ["memory-management"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
full = ["memquota"]
default = []
memquota = []

[dependencies]
derive-deftly = { version = "~1.6.0", features = ["full", "beta"] }
itertools = "0.14.0"
paste = "1.0.3"
void = "1"

[dev-dependencies]
safelog = { path = "../safelog", version = "0.7.0" }
serde_json = "1.0.50"
