[package]
name = "tor-dirmgr"
version = "0.0.3"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Bootstrap and update an accurate Tor network directory"
keywords = ["tor", "arti", "download", "async"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["mmap"]
mmap = ["memmap2"]
static = ["rusqlite/bundled"]
# (Incomplete) support for downloading and storing router descriptors
routerdesc = ["tor-dirclient/routerdesc"]

[dependencies]
retry-error = { path = "../retry-error", version = "0.0.3"}
tor-checkable = { path = "../tor-checkable", version = "0.0.3"}
tor-circmgr = { path = "../tor-circmgr", version = "0.0.3"}
tor-config = { path = "../tor-config", version = "0.0.3"}
tor-consdiff = { path = "../tor-consdiff", version = "0.0.3"}
tor-dirclient = { path = "../tor-dirclient", version = "0.0.3"}
tor-netdir = { path = "../tor-netdir", version = "0.0.3"}
tor-netdoc = { path = "../tor-netdoc", version = "0.0.3"}
tor-llcrypto = { path = "../tor-llcrypto", version = "0.0.3"}
tor-rtcompat = { path = "../tor-rtcompat", version = "0.0.3"}

async-trait = "0.1.2"
base64 = "0.13.0"
derive_builder = "0.10"
digest = "0.10.0"
event-listener = "2"
futures = "0.3"
fslock = { version = "0.2.0" }
hex = "0.4"
itertools = "0.10.1"
tracing = "0.1.18"
memmap2 = { version = "0.5.0", optional = true }
postage = { version = "0.4", default-features = false, features = [
    "futures-traits",
] }
rand = "0.8"
rusqlite = { version = "0.26.3", features = ["time"] }
serde = { version = "1.0.103", features = ["derive"] }
signature = "1"
thiserror = "1"
time = { version = "0.3", features = ["formatting", "parsing"] }
humantime-serde = "1"

[dev-dependencies]
futures-await-test = "0.3.0"
hex-literal = "0.3"
tempfile = "3"
tor-rtcompat = { path = "../tor-rtcompat", version = "0.0.3", features = [
    "tokio",
] }
once_cell = "1"
