[package]
name = "tor-dirmgr"
version = "0.14.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Bootstrap and update an accurate Tor network directory"
keywords = ["tor", "arti", "download", "async"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["mmap", "compression"]
full = [
    "routerdesc",
    "bridge-client",
    "default",
    "fs-mistrust/full",
    "retry-error/full",
    "safelog/full",
    "tor-basic-utils/full",
    "tor-checkable/full",
    "tor-circmgr/full",
    "tor-config/full",
    "tor-consdiff/full",
    "tor-dirclient/full",
    "tor-error/full",
    "tor-guardmgr/full",
    "tor-llcrypto/full",
    "tor-netdir/full",
    "tor-netdoc/full",
    "tor-proto/full",
    "tor-rtcompat/full",
    "tor-geoip?/full",
    "tor-async-utils/full", "tor-persist/full",
]
experimental = ["experimental-api", "dirfilter", "geoip"]
bridge-client = ["tor-circmgr/specific-relay", "tor-guardmgr/bridge-client", "routerdesc"]

mmap = ["memmap2"]
static = ["rusqlite/bundled", "__is_nonadditive"]
compression = ["tor-dirclient/xz", "tor-dirclient/zstd"]
# (Incomplete) support for downloading and storing router descriptors
routerdesc = ["tor-dirclient/routerdesc"]
dirfilter = ["__is_experimental"]
geoip = ["tor-netdir/geoip", "tor-geoip", "__is_experimental"]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental-api = ["__is_experimental"]

__is_nonadditive = []
__is_experimental = []

[dependencies]
async-trait = "0.1.54"
base64ct = "1.5.1"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
derive_more = "0.99.3"
digest = "0.10.0"
educe = "0.4.6"
event-listener = "4"
fs-mistrust = { path = "../fs-mistrust", version = "0.7.6" }
fslock = { version = "0.2.0" }
futures = "0.3.14"
hex = "0.4"
humantime = "2"
humantime-serde = "1.1.1"
itertools = "0.12.0"
memmap2 = { version = "0.9.0", optional = true }
once_cell = "1"
paste = "1"
postage = { version = "0.5.0", default-features = false, features = ["futures-traits"] }
rand = "0.8"
retry-error = { path = "../retry-error", version = "0.5.0" }
rusqlite = { version = "0.30.0", features = ["time"] }
safelog = { path = "../safelog", version = "0.3.2" }
scopeguard = "1"
serde = { version = "1.0.103", features = ["derive"] }
signature = "1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
time = { version = "0.3.20", features = ["formatting", "parsing"] }
tor-async-utils = { version = "0.1.5", path = "../tor-async-utils" }
tor-basic-utils = { path = "../tor-basic-utils", version = "0.8.0" }
tor-checkable = { path = "../tor-checkable", version = "0.6.0" }
tor-circmgr = { path = "../tor-circmgr", version = "0.14.0" }
tor-config = { path = "../tor-config", version = "0.10.0" }
tor-consdiff = { path = "../tor-consdiff", version = "0.6.0" }
tor-dirclient = { path = "../tor-dirclient", version = "0.12.0", default-features = false }
tor-error = { path = "../tor-error", version = "0.6.0", features = ["tracing"] }
tor-geoip = { path = "../tor-geoip", version = "0.2.0", optional = true }
tor-guardmgr = { path = "../tor-guardmgr", version = "0.13.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.6.1" }
tor-netdir = { path = "../tor-netdir", version = "0.11.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.11.0" }
tor-persist = { path = "../tor-persist", version = "0.9.0" }
tor-proto = { path = "../tor-proto", version = "0.15.0" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.9.7" }
tracing = "0.1.36"

[dev-dependencies]
anyhow = "1.0.23"
float_eq = "1.0.0"
hex-literal = "0.4"
tempfile = "3"
tor-linkspec = { path = "../tor-linkspec", version = "0.10.0" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.9.7", features = ["tokio", "native-tls"] }
tor-rtmock = { path = "../tor-rtmock", version = "0.12.0" }
tracing-test = "0.2"
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
