[package]
name = "download-manager"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
arti-client = { path = "../../../crates/arti-client", features = [ "bridge-client", "pt-client" ] }
arti-hyper = { path = "../../../crates/arti-hyper", features = ["default"] }
futures = "0.3.28"
hyper = { version = "0.14", features = ["http1", "client", "runtime"] }
sha2 = "0.10.7"
thiserror = "2"
tls-api = "0.9.0"
tls-api-native-tls = "0.9.0"
tokio = { version = "1.7", features = ["full"] }
tor-rtcompat = { path = "../../../crates/tor-rtcompat" }
tracing = "0.1"
tracing-subscriber = "0.3.17"

[features]
full = ["arti-client/full", "arti-hyper/full", "tor-rtcompat/full"]
