[package]
name = "tor-circmgr"
version = "0.7.3"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Manage a set of anonymous circuits over the Tor network"
keywords = ["tor", "arti", "async"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]

default = []
full = ["specific-relay"]
specific-relay = []

# Enable testing-only APIs.  APIs under this feature are not
# covered by semver.
testing = ["tor-guardmgr/testing"]

# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".
experimental = ["experimental-api", "hs-client", "hs-service"]
experimental-api = ["visibility"]
hs-client = ["hs-common"]
hs-service = ["hs-common"]
hs-common = ["tor-hscrypto"]

[dependencies]
async-trait = "0.1.2"
bounded-vec-deque = "0.1"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
derive_more = "0.99.3"
downcast-rs = "1.2.0"
dyn-clone = "1.0.4"
educe = "0.4.6"
futures = "0.3.14"
humantime-serde = "1.1.1"
itertools = "0.10.1"
once_cell = "1"
pin-project = "1"
rand = "0.8"
retry-error = { path = "../retry-error", version = "0.3.0" }
safelog = { path = "../safelog", version = "0.2.2" }
serde = { version = "1.0.103", features = ["derive"] }
static_assertions = "1"
thiserror = "1"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.6.0" }
tor-chanmgr = { path = "../tor-chanmgr", version = "0.8.3" }
tor-config = { path = "../tor-config", version = "0.8.0" }
tor-error = { path = "../tor-error", version = "0.4.1" }
tor-guardmgr = { path = "../tor-guardmgr", version = "0.8.2" }
tor-hscrypto = { path = "../tor-hscrypto", version = "0.1.2", optional = true }
tor-linkspec = { path = "../tor-linkspec", version = "0.6.3" }
tor-netdir = { path = "../tor-netdir", version = "0.8.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.6.3" }
tor-persist = { path = "../tor-persist", version = "0.6.2" }
tor-proto = { path = "../tor-proto", version = "0.9.1" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1" }
tracing = "0.1.18"
visibility = { version = "0.0.1", optional = true }
weak-table = "0.3.0"

[dev-dependencies]
futures-await-test = "0.3.0"
tor-guardmgr = { path = "../tor-guardmgr", version = "0.8.2", features = [
    "testing",
] }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.4.3" }
tor-netdir = { path = "../tor-netdir", version = "0.8.0", features = [
    "testing",
] }
tor-persist = { path = "../tor-persist", version = "0.6.2", features = [
    "testing",
] }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1", features = [
    "tokio",
    "native-tls",
] }
tor-rtmock = { path = "../tor-rtmock", version = "0.7.2" }
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
