[package]
name = "tor-dircommon"
version = "0.39.0"
authors = [
    "The Tor Project, Inc.",
    "Nick Mathewson <nickm@torproject.org>",
    "Clara Engler <cve@torproject.org>",
]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Common primitives for the Tor directory specification"
keywords = ["tor", "arti", "download", "async"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
base64ct = "1.8.0"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
getset = "0.1.6"
humantime = "2"
humantime-serde = "1.1.1"
serde = { version = "1.0.103", features = ["derive"] }
tor-basic-utils = { path = "../tor-basic-utils", version = "0.39.0" }
tor-checkable = { path = "../tor-checkable", version = "0.39.0" }
tor-config = { path = "../tor-config", version = "0.39.0" }
tor-linkspec = { path = "../tor-linkspec", version = "0.39.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.39.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.39.0" }
tracing = "0.1.41"

[dev-dependencies]
toml = "0.9.6"

[features]
full = [
    "tor-basic-utils/full",
    "tor-checkable/full",
    "tor-config/full",
    "tor-linkspec/full",
    "tor-llcrypto/full",
    "tor-netdoc/full",
]
