[package]
name = "tor-dircommon"
version = "0.34.0"
authors = [
    "The Tor Project, Inc.",
    "Nick Mathewson <nickm@torproject.org>",
    "Clara Engler <cve@torproject.org>",
]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Common primitives for the Tor directory specification"
keywords = ["tor", "arti", "download", "async"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
serde = { version = "1.0.103", features = ["derive"] }
tor-config = { path = "../tor-config", version = "0.34.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.34.0" }
tor-netdoc = { path = "../tor-netdoc", version = "0.34.0" }
