[package]
name = "arti"
version = "0.1.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2018"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A rust implementation of the Tor privacy tools."
keywords = [ "tor", "arti", "privacy", "anonymity" ]
categories = [ "command-line-utilities", "cryptography" ]
repository="https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = [ "tokio", "native-tls" ]
async-std = [ "arti-client/async-std", "tor-rtcompat/async-std", "async-ctrlc", "once_cell" ]
tokio = [ "tokio-crate", "arti-client/tokio", "tor-rtcompat/tokio" ]
native-tls = [ "arti-client/native-tls", "tor-rtcompat/native-tls" ]
rustls = [ "arti-client/rustls", "tor-rtcompat/rustls" ]
static = [ "static-sqlite", "static-native-tls" ]
static-sqlite = [ "arti-client/static-sqlite" ]
static-native-tls = [ "arti-client/static-native-tls", "native-tls" ]
journald = [ "tracing-journald" ]

[dependencies]
arti-client = { package="arti-client", path = "../arti-client", version = "0.1.0", default-features=false}
tor-error = { path="../tor-error", version = "0.1.0", default-features=false }
tor-rtcompat = { path="../tor-rtcompat", version = "0.1.0", default-features=false }
tor-socksproto = { path="../tor-socksproto", version = "0.1.0"}
arti-config = { path="../arti-config", version = "0.1.0"}

anyhow = "1.0.23"
async-ctrlc = { version = "1.2.0", optional = true }
config = { version = "0.12.0", default-features = false }
cfg-if = "1.0.0"
futures = "0.3.14"
tracing = "0.1.18"
notify = "4.0"
once_cell = { version = "1", optional = true }
rlimit = "0.7.0"
serde = { version = "1.0.103", features = ["derive"] }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
tokio-crate = { package = "tokio", version = "1.7", optional = true, features = ["signal"] }
clap = "2.33.0"
tracing-journald = { version = "0.2.0", optional = true }
tracing-appender = "0.2.0"
trust-dns-proto = "0.21.1"

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = [ "winerror" ] }
