[package]
name = "arti"
version = "1.2.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A rust implementation of the Tor privacy tools."
keywords = ["tor", "arti", "privacy", "anonymity"]
categories = ["command-line-utilities", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = [
    "tokio",
    "native-tls",
    "dns-proxy",
    "harden",
    "compression",
    "bridge-client",
    "pt-client",
    "onion-service-client",
]

full = [
    "onion-service-client",
    "onion-service-service",
    "async-std",
    "tokio",
    "native-tls",
    "journald",
    "arti-client/full",
    "dns-proxy",
    "harden",
    "compression",
    "bridge-client",
    "pt-client",
    "arti-rpcserver?/full",
    "fs-mistrust/full",
    "safelog/full",
    "tor-config/full",
    "tor-error/full",
    "tor-rtcompat/full",
    "tor-socksproto/full",
    "tor-rpcbase?/full",
    "tor-hsrproxy?/full",
    "tor-hsservice?/full",
]

async-std = [
    "arti-client/async-std",
    "tor-rtcompat/async-std",
    "async-ctrlc",
    "once_cell",
    "signal-hook",
    "signal-hook-async-std",
]
bridge-client = ["arti-client/bridge-client"]
dns-proxy = ["hickory-proto"]
experimental-api = ["arti-client/experimental-api", "visibility", "__is_experimental"]
harden = ["secmem-proc"]
tokio = ["tokio-crate", "arti-client/tokio", "tor-rtcompat/tokio", "tokio-util"]
native-tls = ["arti-client/native-tls", "tor-rtcompat/native-tls"]
onion-service-client = ["arti-client/onion-service-client"]
onion-service-service = ["arti-client/onion-service-service", "tor-hsrproxy", "tor-hsservice"]
pt-client = ["bridge-client", "arti-client/pt-client"]

# This is not nonadditive from a software POV, but we mark it as such because it
# includes code licensed under the old OpenSSL license (which was 4-clause BSD),
# which in turn introduces a GPL-incompatibility.
rustls = ["arti-client/rustls", "tor-rtcompat/rustls", "__is_nonadditive"]

# depends directly on arti-client/static so native-tls doesn't get automatically included
static = ["arti-client/static", "__is_nonadditive"]
static-sqlite = ["arti-client/static-sqlite", "__is_nonadditive"]
static-native-tls = ["arti-client/static-native-tls", "native-tls", "__is_nonadditive"]
journald = ["tracing-journald"]

accel-sha1-asm = ["arti-client/accel-sha1-asm", "__is_nonadditive"]
accel-openssl = ["arti-client/accel-openssl", "__is_nonadditive"]

__is_nonadditive = []

compression = ["arti-client/compression"]

# This feature flag enables experimental features that are not supported. Turning it on may
# void your API.
experimental = ["arti-client/experimental", "experimental-api", "rpc"]
rpc = ["arti-rpcserver", "tor-rpcbase", "__is_experimental"]
__is_experimental = []

[dependencies]
arti-rpcserver = { path = "../arti-rpcserver", version = "0.5.1", optional = true }
anyhow = "1.0.23"
arti-client = { package = "arti-client", path = "../arti-client", version = "0.14.1", default-features = false, features = [
    "anyhow",
] }
async-ctrlc = { version = "1.2.0", optional = true }
backtrace = "0.3.68"
cfg-if = "1.0.0"
clap = { version = "4.3.24", features = ["string", "wrap_help"] }
config = { version = "0.14.0", default-features = false, features = ["toml"] }
derive_builder = { version = "0.11", package = "derive_builder_fork_arti" }
educe = "0.4.6"
fs-mistrust = { path = "../fs-mistrust", version = "0.7.7" }
futures = "0.3.14"
humantime = "2"
humantime-serde = "1.1.1"
itertools = "0.12.0"
libc = "0.2"
notify = { version = "6.0", default-features = false, features = ["macos_kqueue"] }
once_cell = { version = "1", optional = true }
paste = "1"
rlimit = "0.10.1"
safelog = { path = "../safelog", version = "0.3.2" }
secmem-proc = { version = "0.3.0", optional = true }
serde = { version = "1.0.103", features = ["derive"] }
signal-hook = { version = "0.3", optional = true }
signal-hook-async-std = { version = "0.2", optional = true }
thiserror = "1"
time = "0.3.18"
tokio-crate = { package = "tokio", version = "1.7", optional = true, features = ["signal"] }
tokio-util = { version = "0.7.0", features = ["compat"], optional = true }
toml = "0.8.8"
tor-config = { path = "../tor-config", version = "0.11.0" }
tor-error = { path = "../tor-error", version = "0.6.0", default-features = false, features = ["tracing"] }
tor-hsrproxy = { path = "../tor-hsrproxy", version = "0.6.0", optional = true }
tor-hsservice = { path = "../tor-hsservice", version = "0.8.0", optional = true }
tor-rpcbase = { path = "../tor-rpcbase", version = "0.3.0", optional = true }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.10.0", default-features = false }
tor-socksproto = { path = "../tor-socksproto", version = "0.10.0" }
tracing = "0.1.36"
tracing-appender = "0.2.0"
tracing-journald = { version = "0.3.0", optional = true }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
hickory-proto = { version = "0.24.0", optional = true }
visibility = { version = "0.1.0", optional = true }

[dev-dependencies]
derive_more = "0.99.3"
itertools = "0.12.0"
regex = { version = "1", default-features = false, features = ["std"] }
serde_json = "1.0.50"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winerror"] }
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
