[package]
name = "tor-error"
version = "0.5.0"
authors = ["Ian Jackson <iwj@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Provides the unified type-erased error type returned by many (esp. high-level) Tor APIs."
keywords = ["tor", "arti"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"
categories = ["rust-patterns"]

[features]
default = ["backtrace"]
experimental-api = ["rpc"]
rpc = []

[dependencies]
backtrace = { version = "0.3.39", optional = true }
derive_more = "0.99.3"
futures = "0.3"
once_cell = "1"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1"

[dev-dependencies]
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
