[package]
name = "tor-events"
version = "0.0.3"
edition = "2018"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A typed event broadcasting framework for Arti."
keywords = [ "tor", "arti" ]
categories = [ "asynchronous" ]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
async-broadcast = "0.3.2"
futures = "0.3"
tracing = "0.1.18"
once_cell = "1"
thiserror = "1"

[dev-dependencies]
tokio = { version = "1.4", features = ["macros", "rt", "rt-multi-thread", "time"] }
