[package]
name = "tor-events"
version = "0.4.0"
edition = "2021"
rust-version = "1.60"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A typed event broadcasting framework for Arti."
keywords = ["tor", "arti"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
async-broadcast = "0.4.0"
futures = "0.3.14"
once_cell = "1"
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1"
tracing = "0.1.18"

[dev-dependencies]
tokio = { version = "1.7", features = ["macros", "rt", "rt-multi-thread", "time"] }
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
